### ISSUE TITLE
ImportError: No module named novaclient

### ISSUE THREAD

**Issue by shortsteps** [lukaspustina/dynamic-inventory-for-ansible-with-openstack#12]
Hi,

while running` ./openstack_inventory.py --list` I get this error:
```
Traceback (most recent call last):
  File "./openstack_inventory.py", line 40, in <module>
    from novaclient import client
ImportError: No module named novaclient
```

Is there any prerequisite or any package I have to install before running it?
I'm running it from AWX installation (docker container).

$ ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

Thanks a lot

**Comment by shortsteps** [comment]
I partially solved, installing some missing packages 
```
yum install python-devel gcc
pip install --upgrade pip
pip install python-openstackclient
```
Now the error thrown is : 
`ERROR: environment variable 'OS_COMPUTE_API_VERSION' is not defined`

So i set it, and the error changed (according to my OS_IDENTITY_API_VERSION=2) :
`export OS_COMPUTE_API_VERSION=2`

```
./openstack-lukas.py --list    
Traceback (most recent call last):
  File "./openstack-lukas.py", line 127, in <module>
    main(sys.argv)
  File "./openstack-lukas.py", line 57, in main
    for server in nt.servers.list():
  File "/usr/lib/python2.7/site-packages/novaclient/v2/servers.py", line 884, in list
    "servers")
  File "/usr/lib/python2.7/site-packages/novaclient/base.py", line 254, in _list
    resp, body = self.api.client.get(url)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 304, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 77, in request
    **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 463, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 189, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 573, in request
    auth_headers = self.get_auth_headers(auth)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 900, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/plugin.py", line 95, in get_headers
    token = self.get_token(session)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 88, in get_token
    return self.get_access(session).auth_token
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 134, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/generic/base.py", line 198, in get_auth_ref
    return self._plugin.get_auth_ref(session, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/v2.py", line 63, in get_auth_ref
    authenticated=False, log=False)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 848, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 737, in request
    raise exceptions.from_response(resp, method, url)
keystoneauth1.exceptions.http.Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-b4c168e8-33ab-4adf-bde7-45463b107cf5)

```
All openstack commands still work correctly, so the rc file is consistent.

**Comment by lukaspustina** [comment]
Hi there,

it seems, the script fails to authenticate. Did you set the environment variables `OS_AUTH_URL`, `OS_USERNAME`, `OS_PASSWORD`, and `OS_TENANT_NAME` accordingly?

**Comment by shortsteps** [comment]
Yes, I set them before executing it. Here you are my `env` output:
```
[root@awx ~]# env | grep OS_
OS_REGION_NAME=regionOne
OS_TENANT_ID=b04c54ca3bc64b109182b87caa432f4a
OS_IDENTITY_API_VERSION=2
OS_PASSWORD=4b55fff1f7f0d56739e8
OS_AUTH_URL=https://HOSTNAME:PORT/v2.0
OS_USERNAME=1-4GCPMNC
OS_TENANT_NAME=93413547190
OS_ENDPOINT_TYPE=publicURL
```
For example at this stage, `openstack image list` works correctly.
For your script I exported also OS_COMPUTE_API_VERSION=2 as said in above comment.

Openstack command still works, but your script fails to authenticate. Any idea?
Should I user v3.0 auth endpoint?

Thanks a lot

**Comment by saurav955** [comment]
Hey Guys,

Any work arounds???

**Comment by lukaspustina** [comment]
@saurav955 Hi. I can't recommend using this script anymore. OpenStack evolved a lot since 2 years ago. Please refer to something like "https://docs.openstack.org/openstack-ansible/newton/developer-docs/inventory.html".
